import React, { useCallback, useEffect, useState } from 'react';
import { Banknote, ChevronDown, ChevronUp, Loader2, RefreshCw } from 'lucide-react';
import Pagination from '../../components/Pagination';
import api from '../../api';

const currency = value => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value || 0));
const statusText = status => ({ draft: 'Draf · belum terlihat karyawan', finalized: 'Final · slip tersedia', paid: 'Dibayar' }[status] || status);

export default function AdminPayroll() {
    const now = new Date();
    const [month, setMonth] = useState(now.getMonth() + 1);
    const [year, setYear] = useState(now.getFullYear());
    const [runs, setRuns] = useState([]); const [pagination, setPagination] = useState(null); const [page, setPage] = useState(1);
    const [details, setDetails] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
    const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await api.get('/admin/payroll/runs', { params: { page } }); setRuns(response.data?.data || []); setPagination(response.data); } catch (e) { setError(e.response?.data?.message || 'Riwayat payroll gagal dimuat.'); } finally { setLoading(false); } }, [page]);
    useEffect(() => { load(); }, [load]);
    const generate = async e => { e.preventDefault(); setBusy(true); setError(''); try { const response = await api.post('/admin/payroll/runs', { period_month: Number(month), period_year: Number(year) }); setDetails(null); await load(); if (response.data?.data?.id) await openDetails(response.data.data.id); } catch (e) { setError(e.response?.data?.message || Object.values(e.response?.data?.errors || {})[0]?.[0] || 'Payroll gagal dibuat. Periksa komponen, absensi, dan konfigurasi tarif.'); } finally { setBusy(false); } };
    const openDetails = async id => { setBusy(true); setError(''); try { const response = await api.get(`/admin/payroll/runs/${id}`); setDetails(response.data); } catch (e) { setError(e.response?.data?.message || 'Rincian payroll gagal dimuat.'); } finally { setBusy(false); } };
    const changeStatus = async (run, action, promptText) => { if (!window.confirm(promptText)) return; setBusy(true); setError(''); try { await api.post(`/admin/payroll/runs/${run.id}/${action}`); await load(); if (details?.run?.id === run.id) await openDetails(run.id); } catch (e) { setError(e.response?.data?.message || 'Status payroll gagal diperbarui.'); } finally { setBusy(false); } };
    const periodLabel = run => run.period_start && run.period_end ? `${new Date(`${run.period_start}T00:00:00`).toLocaleDateString('id-ID')} – ${new Date(`${run.period_end}T00:00:00`).toLocaleDateString('id-ID')}` : `${run.period_month}/${run.period_year}`;

    return <div className="mx-auto max-w-7xl space-y-6 p-5 md:p-8">
        <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="rounded-2xl bg-emerald-100 p-3 text-emerald-800"><Banknote /></span><div><h1 className="text-3xl font-bold text-slate-900">Penggajian</h1><p className="mt-1 text-slate-500">Buat draf, tinjau perhitungan, finalisasi, lalu tandai pembayaran.</p></div></div><button onClick={load} className="inline-flex items-center gap-2 self-start rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700"><RefreshCw className="h-4 w-4"/>Muat ulang</button></header>
        <div className="rounded-2xl border border-emerald-200 bg-gradient-to-br from-emerald-50 to-white p-5 md:p-7"><h2 className="font-bold text-slate-900">Buat draf periode gaji</h2><p className="mt-1 text-sm text-slate-600">Rentang rekap mengikuti pengaturan payroll; data karyawan baru menerima slip setelah draf difinalisasi.</p><form onSubmit={generate} className="mt-4 flex flex-wrap items-end gap-3"><label className="text-sm font-medium">Bulan gaji<select className="mt-1 block rounded-lg border border-slate-200 bg-white px-3 py-2" value={month} onChange={e=>setMonth(e.target.value)}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(Number(year),i,1).toLocaleDateString('id-ID',{month:'long'})}</option>)}</select></label><label className="text-sm font-medium">Tahun<input className="mt-1 block w-28 rounded-lg border border-slate-200 bg-white px-3 py-2" type="number" min="2020" max="2100" value={year} onChange={e=>setYear(e.target.value)}/></label><button disabled={busy} className="rounded-xl bg-emerald-700 px-5 py-2.5 font-semibold text-white disabled:opacity-50">{busy?'Memproses…':'Hitung draf payroll'}</button></form></div>
        {error && <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-rose-800">{error}</div>}
        {loading ? <div className="grid min-h-40 place-items-center"><Loader2 className="animate-spin text-emerald-700"/></div> : <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-bold text-slate-900">Riwayat & status pembayaran</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-4">Periode</th><th className="p-4">Jadwal bayar</th><th className="p-4">Karyawan</th><th className="p-4">Status</th><th className="p-4 text-right">Aksi</th></tr></thead><tbody className="divide-y divide-slate-100">{runs.map(run=><tr key={run.id}><td className="p-4"><b className="block">{new Date(run.period_year,(run.period_month||1)-1,1).toLocaleDateString('id-ID',{month:'long',year:'numeric'})}</b><small className="text-slate-500">Rekap {periodLabel(run)}</small></td><td className="p-4">{run.scheduled_payment_date?new Date(`${run.scheduled_payment_date}T00:00:00`).toLocaleDateString('id-ID'):'—'}</td><td className="p-4">{run.payslips_count ?? '—'}</td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${run.status==='paid'?'bg-blue-100 text-blue-800':run.status==='finalized'?'bg-emerald-100 text-emerald-800':'bg-amber-100 text-amber-800'}`}>{statusText(run.status)}</span></td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={()=>details?.run?.id===run.id?setDetails(null):openDetails(run.id)} className="inline-flex items-center gap-1 rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold">Rincian {details?.run?.id===run.id?<ChevronUp className="h-4 w-4"/>:<ChevronDown className="h-4 w-4"/>}</button>{run.status==='draft'&&<button disabled={busy} onClick={()=>changeStatus(run,'finalize','Finalisasi akan membuat rincian gaji dapat dilihat oleh karyawan. Pastikan semua angka sudah ditinjau.')} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white">Finalisasi & terbitkan</button>}{run.status==='finalized'&&<button disabled={busy} onClick={()=>changeStatus(run,'paid','Tandai periode ini telah dibayar kepada karyawan?')} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-bold text-white">Tandai dibayar</button>}</div></td></tr>)}</tbody></table>{!runs.length&&<div className="p-12 text-center text-slate-500">Belum ada proses payroll.</div>}</div><Pagination pagination={pagination} onPageChange={setPage}/></section>}
        {details?.run && <section className="space-y-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-7"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-900">Rincian slip · {periodLabel(details.run)}</h2><p className="text-sm text-slate-500">Status: {statusText(details.run.status)} · Komponen perusahaan dan karyawan dipisah.</p></div><button onClick={()=>setDetails(null)} className="text-sm font-semibold text-slate-500">Tutup</button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Karyawan',details.summary?.total_employees],['Gaji pokok',currency(details.summary?.total_basic_salary)],['Potongan pekerja',currency(details.summary?.total_deductions)],['Iuran perusahaan',currency(details.summary?.total_employer_contributions)],['Gaji bersih dibayarkan',currency(details.summary?.total_net_salary)]].map(([label,value])=><div key={label} className="rounded-xl bg-slate-50 p-4"><small className="text-slate-500">{label}</small><b className="mt-1 block text-slate-900">{value}</b></div>)}</div><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Karyawan</th><th className="p-3">Alpha</th><th className="p-3">Bruto</th><th className="p-3">Potongan</th><th className="p-3 text-right">Bersih</th></tr></thead><tbody className="divide-y divide-slate-100">{(details.payslips||[]).map(slip=><tr key={slip.id}><td className="p-3"><b>{slip.employee?.full_name||'Karyawan'}</b><small className="block text-slate-500">{slip.employee?.employee_number||''}</small></td><td className="p-3">{slip.attendance_absence_days||0} hari · {currency(slip.attendance_deduction_amount)}</td><td className="p-3">{currency(slip.gross_salary)}</td><td className="p-3">{currency(slip.total_deductions)}</td><td className="p-3 text-right font-bold text-emerald-800">{currency(slip.net_salary)}</td></tr>)}</tbody></table></div></section>}
        {busy && <div className="fixed bottom-5 right-5 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm text-white shadow-xl"><Loader2 className="h-4 w-4 animate-spin"/>Memproses payroll</div>}
    </div>;
}
